#!/bin/sh
set -x
useradd -l -u ${USER_UID} -r -g 0 -d ${CONTAINER_SCRIPTS_ROOT} -s /sbin/nologin -c "${USER_NAME} application user" ${USER_NAME}
chown -R ${USER_UID}:0 ${CONTAINER_SCRIPTS_ROOT}
find ${CONTAINER_SCRIPTS_ROOT} -type d -exec chmod g+x {} +
chmod -R g+w ${CONTAINER_SCRIPTS_ROOT} /etc/passwd
